# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-config-bucket
  description: This module creates an S3 bucket suitable for storing `AWS Config` data
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component



